[package]
name = 'jsdotlua/roact-compat'
description = 'https://github.com/grilme99/CorePackages'
version = '17.0.1'
license = 'MIT + Apache 2.0'
authors = ['Roblox Corporation']
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
LuauPolyfill = 'jsdotlua/luau-polyfill@1.2.3'
React = 'jsdotlua/react@17.0.1-rc.19'
ReactRoblox = 'jsdotlua/react-roblox@17.0.1-rc.19'
Shared = 'jsdotlua/shared@17.0.1-rc.19'
